export const CANVAS_CONFIG = {
  MIN_ZOOM: 0.2,
  MAX_ZOOM: 5,

  ZOOM_DELTA_IN: 1.2,
  ZOOM_DELTA_OUT: 0.8,

  DRAW_THROTTLE_MS: 16,
  MIN_POINT_DISTANCE: 2,

  ERASER_RADIUS: 24,

  MAX_STACK_SIZE: 50,

  SELECTION_BOX_PADDING_RATIO: 0.05,
  RESIZE_HANDLE_RADIUS: 5,
  MIN_RESIZE_SIZE: 1,
} as const;
